EEA38_PLUS_UK_COUNTRIES = [
    "Albania",
    "Austria", 
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Malta",
    "Moldova",
    "Montenegro",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "Ukraine",
    "United Kingdom"
]

keywords_climate_eng = [
    # Original keywords
    "climate change",
    "changing climate",
    "climate emergency",
    "climate action",
    "climate crisis",
    "climate decay",
    "global warming",
    "extreme weather",
    "global environmental change",
    "climate variability",
    "greenhouse gas",
    "greenhouse-gas",
    "low carbon",
    "GHG",
    "GHGs",
    "renewable energy",
    "carbon emission",
    "carbon emissions",
    "carbon dioxide",
    "carbon-dioxide",
    "co2 emission",
    "co2 emissions",
    "methane emission",
    "methane emissions",
    "climate pollutant",
    "climate pollutants",
    "decarbonization",
    "decarbonisation",
    "carbon neutral",
    "carbon-neutral",
    "carbon neutrality",
    "net-zero",
    "net zero",
    
    # Climate Impacts
    "sea level rise",
    "ocean acidification",
    "coral bleaching",
    "ice sheet melting",
    "glacier retreat",
    "permafrost thaw",
    "drought",
    "flooding",
    "heat wave",
    "heatwave",
    "wildfire",
    "forest fire",
    "climate refugee",
    "climate migration",
    "climate vulnerability",
    "climate resilience",
    "climate adaptation",
    "climate mitigation",
    "climate impact",
    
    # Climate Policy & Governance
    "Paris Agreement",
    "climate treaty",
    "climate accord",
    "carbon tax",
    "cap and trade",
    "emissions trading",
    "climate policy",
    "climate legislation",
    "climate governance",
    "nationally determined contributions",
    "NDC",
    "climate finance",
    "green deal",
    "climate justice",
    "environmental justice",
    "just transition",
    "climate target",
    "emission reduction target",
    "1.5 degrees",
    "2 degrees celsius",
    
    # Specific Renewable Energy Solutions
    "solar power",
    "solar energy",
    "wind power",
    "wind energy",
    "wind turbine",
    "offshore wind",
    "hydropower",
    "hydroelectric",
    "geothermal energy",
    "tidal energy",
    "wave energy",
    "bioenergy",
    "green hydrogen",
    "electric vehicle",
    "EV",
    "heat pump",
    
    # Bonus: Related Important Terms
    "carbon footprint",
    "carbon offset",
    "carbon sequestration",
    "carbon sink",
    "carbon capture",
    "nature-based solution",
    "reforestation",
    "afforestation",
    "coal phase-out",
    "stranded asset",
    "climate science",
    "IPCC",
    "climate model"
]

keywords_climate_eng_reduced = [
    # Add standalone terms
    "climate",
    "carbon",
    "methane",
    "greenhouse",
    
    # Original keywords (without those containing "climate" or "carbon")
    "global warming",
    "extreme weather",
    
    # Climate Impacts (without "climate")
    "drought",
    "flood",
    "heat wave",
    "heatwave",
    "wildfire",
    "forest fire",
    
    # Climate Policy & Governance (without "climate")
    "emissions",
    "green deal",
    
    # Specific Renewable Energy Solutions
    "wind power",
    "wind energy",
    "wind turbine",
    "wind turbines",
    "offshore wind",
    "solar power",
    "solar energy",
    "solar panels",
    "renewable energy",
    "electric vehicle",
    "EV",
    "EVs"
]

concepts_climate = [
    "climate change",
    "global warming",
    "climate impacts",
    "climate effects",
    "renewable energy",
    "electric vehicle",
    "energy policy",
    "emissions trading",
    "climate politics",
    "climate justice",
    "energy transition",
    "european green deal",
    "climate finance",
    "climate legislation",
    "climate governance"
]

turkish_translations = [
    'CO2 emisyonları',
    'iklim eylemi',
    'karbondioksit emisyonları',
    'karbon emisyonları',
    'karbon nötr',
    'iklim çöküşü',
    'iklim değişikliği',
    'iklim krizi',
    'iklim acil durumu',
    'iklim alarmı',
    'karbonsuzlaşma',
    'dekarbonizasyon',
    'kuraklık',
    'aşırı hava olayı',
    'ekstrem hava olayı',
    'sel',
    'taşkın',
    'küresel ısınma',
    'sera gazı',
    'sıcak dalgası',
    'sıcak hava dönemi',
    'net sıfır',
    'net sıfır emisyon',
    'güneş enerjisi',
    'ılık hava dönemi',
    'rüzgar enerjisi'
]

russian_translations = [
    'выбросы CO2',
    'климатические действия',
    'борьба с изменением климата',
    'выбросы углекислого газа',
    'углеродные выбросы',
    'выбросы углерода',
    'углеродно-нейтральный',
    'карбоново-нейтральный',
    'климатический коллапс',
    'изменение климата',
    'климатический кризис',
    'климатическая чрезвычайная ситуация',
    'климатическая угроза',
    'декарбонизация',
    'засуха',
    'экстремальное погодное явление',
    'наводнение',
    'паводок',
    'затопление',
    'глобальное потепление',
    'парниковый газ',
    'волна жары',
    'тепловая волна',
    'жаркий период',
    'нулевой баланс выбросов',
    'углеродная нейтральность',
    'солнечная энергия',
    'теплый период',
    'энергия ветра',
    'ветровая энергия'
]

icelandic_translations = [
    'CO2 losun',
    'loftslagsaðgerðir',
    'koltvísýringslosun',
    'kolefnisdíoxíðslosun',
    'kolefnislosun',
    'kolefnishlutlaus',
    'loftslagshrun',
    'loftslagsbreytingar',
    'loftslagskreppa',
    'loftslagsneyðarástand',
    'kolefnisbrottnám',
    'afkolun',
    'þurrkur',
    'öfgaveðursatburður',
    'öfgaveður',
    'flóð',
    'yfirfall',
    'hlýnun jarðar',
    'hnatthlýnun',
    'gróðurhúsalofttegundir',
    'gróðurhúsagas',
    'hitabylgja',
    'hitatímabil',
    'núll nettólosun',
    'kolefnishlutleysa',
    'sólarorka',
    'sólarrafmagn',
    'hlýindi',
    'hlýindatímabil',
    'vindorka',
    'vindrafmagn'
]

albanian_translations = [
    'emetimet e CO2',
    'veprimi klimatik',
    'aksioni klimatik',
    'emetimet e dioksidit të karbonit',
    'emetimet e karbonit',
    'neutral ndaj karbonit',
    'karbon-neutral',
    'kolapsi klimatik',
    'shkatërrimi klimatik',
    'ndryshimet klimatike',
    'ndryshimi klimatik',
    'kriza klimatike',
    'emergjenca klimatike',
    'gjendja e jashtëzakonshme klimatike',
    'dekarbonizimi',
    'thatësirë',
    'ngjarje ekstreme të motit',
    'fenomene ekstreme atmosferike',
    'përmbytje',
    'vërshim',
    'ngrohja globale',
    'gazi serë',
    'gazrat serrë',
    'valë të nxehtit',
    'valë vapë',
    'periudhë e nxehtë',
    'zero neto',
    'bilanci zero i emetimeve',
    'energjia diellore',
    'periudhë e ngrohtë',
    'energjia e erës',
    'energjia nga era'
]

ukrainian_translations = [
    'викиди CO2',
    'кліматичні дії',
    'боротьба зі зміною клімату',
    'викиди вуглекислого газу',
    'викиди діоксиду вуглецю',
    'вуглецеві викиди',
    'викиди вуглецю',
    'вуглецево-нейтральний',
    'карбон-нейтральний',
    'кліматичний колапс',
    'руйнування клімату',
    'зміна клімату',
    'кліматичні зміни',
    'кліматична криза',
    'кліматична надзвичайна ситуація',
    'кліматична загроза',
    'декарбонізація',
    'посуха',
    'екстремальне погодне явище',
    'повінь',
    'паводок',
    'затоплення',
    'глобальне потепління',
    'парниковий газ',
    'хвиля спеки',
    'тепловий удар',
    'спекотний період',
    'нульовий баланс викидів',
    'вуглецева нейтральність',
    'сонячна енергія',
    'теплий період',
    'енергія вітру',
    'вітрова енергія'
]

serbian_translations = [
    'емисије CO2',
    'emisije CO2',
    'климатске акције',
    'klimatske akcije',
    'борба против климатских промена',
    'borba protiv klimatskih promena',
    'емисије угљен-диоксида',
    'emisije ugljen-dioksida',
    'угљеничне емисије',
    'ugljенične emisije',
    'емисије угљеника',
    'emisije ugljenika',
    'карбонски неутралан',
    'karbonski neutralan',
    'угљенично неутралан',
    'ugljенično neutralan',
    'климатски колапс',
    'klimatski kolaps',
    'климатски слом',
    'klimatski slom',
    'климатске промене',
    'klimatske promene',
    'климатска криза',
    'klimatska kriza',
    'климатско ванредно стање',
    'klimatsko vanredno stanje',
    'климатска хитност',
    'klimatska hitnost',
    'декарбонизација',
    'dekarbonizacija',
    'суша',
    'suša',
    'екстремни временски догађај',
    'ekstremni vremenski događaj',
    'екстремне временске појаве',
    'ekstremne vremenske pojave',
    'поплава',
    'poplava',
    'плављење',
    'plavljenje',
    'глобално загревање',
    'globalno zagrevanje',
    'глобално отопљавање',
    'globalno otoplјavanje',
    'гас са ефектом стаклене баште',
    'gas sa efektom staklene bašte',
    'стакленички гас',
    'staklenički gas',
    'топлотни талас',
    'toplotni talas',
    'период врућине',
    'period vručine',
    'нето нула емисија',
    'neto nula emisija',
    'нулти биланс емисија',
    'nulti bilans emisija',
    'сунчева енергија',
    'sunčeva energija',
    'соларна енергија',
    'solarna energija',
    'топао период',
    'topao period',
    'енергија ветра',
    'energija vetra',
    'ветрена енергија',
    'vetrena energija'
]

macedonian_translations = [
    'емисии на CO2',
    'климатски акции',
    'борба против климатските промени',
    'емисии на јаглерод диоксид',
    'јагленични емисии',
    'емисии на јаглерод',
    'јагленично неутрален',
    'карбонски неутрален',
    'климатски колапс',
    'климатски слом',
    'климатски промени',
    'климатска криза',
    'климатска вонредна состојба',
    'климатска итност',
    'декарбонизација',
    'суша',
    'екстремен временски настан',
    'екстремни временски појави',
    'поплава',
    'поплавување',
    'глобално затоплување',
    'стакленички гас',
    'топлотен бран',
    'период на топлотија',
    'жешки период',
    'нето нула емисии',
    'нулта нето емисија',
    'сончева енергија',
    'соларна енергија',
    'топол период',
    'енергија на ветер',
    'ветерна енергија'
]